//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class knowhauEntities : DbContext
    {
        public knowhauEntities()
            : base("name=knowhauEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<BA> BAs { get; set; }
        public virtual DbSet<BEACON> BEACONs { get; set; }
        public virtual DbSet<CONTENT> CONTENTs { get; set; }
        public virtual DbSet<HISTORIC> HISTORICs { get; set; }
        public virtual DbSet<LOGMOBILEAPP> LOGMOBILEAPPs { get; set; }
        public virtual DbSet<LOGWEBAPP> LOGWEBAPPs { get; set; }
        public virtual DbSet<SUPERADMIN> SUPERADMINs { get; set; }
        public virtual DbSet<USERM> USERMs { get; set; }
    }
}
