//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIC
    {
        public int historicID { get; set; }
        public int contentID { get; set; }
        public string userMAIL { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual CONTENT CONTENT { get; set; }
        public virtual USERM USERM { get; set; }
    }
}
